In [1]:
import numpy as np
data = np.array([22,31,41,51,70])

mean = np.mean(data)
std_dev = np.std(data)

print("Mean:",mean)
print("Standard Deviation:",std_dev)

Mean: 43.0
Standard Deviation: 16.625281952496323


In [2]:
import numpy as np

matrix = np.random.randint(1, 50, size=(5, 5))

print("Random 5x5 matrix:")
print(matrix)

min_row = np.min(matrix, axis=1)
max_row = np.max(matrix, axis=1)

print("\nMinimum values along each row:")
print(min_row)
print("\nMaximum values along each row:")
print(max_row)

min_col = np.min(matrix, axis=0)
max_col = np.max(matrix, axis=0)

print("\nMinimum values along each column:")
print(min_col)
print("\nMaximum values along each column:")
print(max_col)

Random 5x5 matrix:
[[44 39 31  5 42]
 [27 22 23  4 15]
 [30 37 46 38 47]
 [48 19  8 29 24]
 [49 11 34 31 18]]

Minimum values along each row:
[ 5  4 30  8 11]

Maximum values along each row:
[44 27 47 48 49]

Minimum values along each column:
[27 11  8  4 15]

Maximum values along each column:
[49 39 46 38 47]


In [3]:
import numpy as np

def cosine(a, b):
    dot_product = np.dot(a, b)
    a = np.linalg.norm(a)
    b = np.linalg.norm(b)
    similarity = dot_product / (a * b)
    return similarity

vector1 = np.array([23, 66, 93])
vector2 = np.array([50, 42, 74])

print("Cosine Similarity:", cosine(vector1, vector2))

Cosine Similarity: 0.9410051732510097
